# Generated by Django 4.0.4 on 2022-06-03 21:30

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_candidate', models.BooleanField(default=False, verbose_name='Кандидат')),
                ('is_employer', models.BooleanField(default=False, verbose_name='Роботодавець')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='Номер телефону')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 0, 30, 53, 305540), verbose_name='Дата реєстрації')),
                ('education_level', models.CharField(choices=[('середня школа', 'середня школа'), ('старша школа', 'старша школа'), ('коледж', 'коледж'), ('бакалавр', 'бакалавр'), ('магістр', 'магістр')], max_length=50, verbose_name='Освіта')),
                ('experience_level', models.CharField(choices=[('без досвіду', 'без досвіду'), ('пів року', 'пів року'), ('більше року', 'більше року'), ('більше 2 років', 'більше 2 років'), ('більше 5 років', 'більше 5 років')], max_length=50, verbose_name='Досвід')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Ваше фото')),
                ('desired_vacancy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бажана вакансія')),
            ],
            options={
                'verbose_name': 'Кандидати',
                'verbose_name_plural': 'Кандидати',
                'ordering': ['creation_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тип кандидата')),
            ],
            options={
                'verbose_name': 'Типи кандидатів',
                'verbose_name_plural': 'Типи кандидатів',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Міста',
                'verbose_name_plural': 'Міста',
                'ordering': ['title', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва компанії')),
                ('website_url', models.CharField(max_length=100, verbose_name='Адреса веб-сайту команії')),
                ('workers_count', models.CharField(choices=[('0–10', '0–10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100–500', '100–500'), ('500–1000+', '500–1000+')], default='10-20', max_length=20, verbose_name='Кількість пацівників')),
                ('description', models.TextField(max_length=1500, verbose_name='Опис команії')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Компания')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='work4you_app.category', verbose_name='Категорія')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.city', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Компанії',
                'verbose_name_plural': 'Компанії',
                'ordering': ['city', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone1', models.CharField(max_length=20, null=True, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон 2')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Країни',
                'verbose_name_plural': 'Країни',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюти',
                'verbose_name_plural': 'Валюти',
                'ordering': ['-title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тип зайнятості')),
            ],
            options={
                'verbose_name': 'Типи зайнятості',
                'verbose_name_plural': 'Типи зайнятості',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва вакансії')),
                ('description', models.TextField(max_length=1500, verbose_name='Опис вакансії')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 0, 30, 53, 300539), verbose_name='Дата додавання')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('education_level', models.CharField(choices=[('середня школа', 'середня школа'), ('старша школа', 'старша школа'), ('коледж', 'коледж'), ('бакалавр', 'бакалавр'), ('магістр', 'магістр')], max_length=50, verbose_name='Освіта')),
                ('experience_level', models.CharField(choices=[('без досвіду', 'без досвіду'), ('пів року', 'пів року'), ('більше року', 'більше року'), ('більше 2 років', 'більше 2 років'), ('більше 5 років', 'більше 5 років')], max_length=50, verbose_name='Досвід')),
                ('candidate_types', models.ManyToManyField(blank=True, null=True, to='work4you_app.candidatetype', verbose_name='Типи кандидатів')),
                ('categories', models.ManyToManyField(to='work4you_app.category', verbose_name='Категорія')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work4you_app.company', verbose_name='Компанія')),
                ('currency', models.ForeignKey(default='грн', max_length=15, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.currency', verbose_name='Валюта')),
                ('employment_type', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.employmenttype', verbose_name='Тип зайнятості')),
            ],
            options={
                'verbose_name': 'Вакансії',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['company', 'salary'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 0, 30, 53, 306540), verbose_name='Дата реєстрації')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.company', verbose_name='Ваша компанія')),
                ('saved_candidates', models.ManyToManyField(blank=True, null=True, to='work4you_app.candidate', verbose_name='Збережені кандидати')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роботодавці',
                'verbose_name_plural': 'Роботодавці',
                'ordering': ['creation_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.contacts', verbose_name='Контакти'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.country'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='saved_vacancies',
            field=models.ManyToManyField(blank=True, null=True, to='work4you_app.vacancy', verbose_name='Збережені вакансії'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
