# Generated by Django 4.0.4 on 2022-05-25 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Міста',
                'verbose_name_plural': 'Міста',
                'ordering': ['title', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва компанії')),
                ('website_url', models.CharField(max_length=100, verbose_name='Адреса веб-сайту команії')),
                ('workers_count', models.PositiveIntegerField(default=1, verbose_name='Кількість пацівників')),
                ('description', models.CharField(max_length=100, verbose_name='Опис команії')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.city', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Компанії',
                'verbose_name_plural': 'Компанії',
                'ordering': ['country', 'city', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Країни',
                'verbose_name_plural': 'Країни',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва вакансії')),
                ('description', models.CharField(max_length=100, verbose_name='Опис вакансії')),
                ('salary_type', models.CharField(choices=[('HOURLY', 'погодинно'), ('DAILY', 'щоденно'), ('WEEKLY', 'щотижня'), ('MONTHLY', 'щомісячно')], max_length=100, verbose_name='Тип вакансії')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 5, 25, 18, 18, 56, 953627), verbose_name='Дата додавання')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('is_for_student', models.BooleanField(default=False, verbose_name='Для студентів')),
                ('is_for_migrant', models.BooleanField(default=False, verbose_name='Для переселенців')),
                ('education_level', models.CharField(choices=[('MIDDLE_SCHOOL', 'Середня школа'), ('GRADUATE_SCHOOL', 'Старша школа'), ('COLLEGE', 'Коледж'), ('BACHELOR', 'Бакалавр'), ('MASTER', 'Магістр')], max_length=50, verbose_name='Освіта')),
                ('experience_level', models.CharField(choices=[('NONE', 'Без досвіду'), ('HALF_YEAR', 'Пів року'), ('ONE_MORE_YEAR', 'Більше року'), ('TWO_MORE_YEAR', 'Більше 2 років'), ('FIVE_MORE_YEAR', 'Більше 5 років')], max_length=50, verbose_name='Досвід')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.category', verbose_name='Категорія')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.company', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Вакансії',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['company', 'category', 'salary'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.country'),
        ),
    ]
