# Generated by Django 4.0.4 on 2022-06-29 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='user',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.candidate'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.employer'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_types',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='work4you_app.employmenttype', verbose_name='Тип зайнятості'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 18, 29, 3, 504319), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.country', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 18, 29, 3, 506318), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 18, 29, 3, 501318), verbose_name='Дата додавання'),
        ),
    ]
