# Generated by Django 4.0.4 on 2022-06-04 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 19, 10, 53, 110971), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.country', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 19, 10, 53, 112981), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 19, 10, 53, 105982), verbose_name='Дата додавання'),
        ),
    ]
