# Generated by Django 4.0.4 on 2022-06-04 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0002_alter_candidate_creation_date_alter_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.candidate'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.employer'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 15, 14, 697867), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 15, 14, 698867), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 15, 14, 694866), verbose_name='Дата додавання'),
        ),
    ]
