# Generated by Django 4.0.4 on 2022-05-25 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0002_alter_city_country_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default='Україна', on_delete=django.db.models.deletion.CASCADE, to='work4you_app.country', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 18, 35, 16, 729131), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('HRYVNIA', '₴'), ('DOLLAR', '$'), ('EURO', '€')], max_length=10, verbose_name='Валюта'),
        ),
    ]
