# Generated by Django 4.0.4 on 2022-05-25 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0003_alter_company_country_alter_vacancy_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work4you_app.company', verbose_name='Команія'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 22, 0, 40, 437311), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_type',
            field=models.CharField(choices=[('HOURLY', 'погодинно'), ('DAILY', 'щоденно'), ('WEEKLY', 'щотижня'), ('MONTHLY', 'щомісячно')], max_length=100, verbose_name='Тип оплати'),
        ),
    ]
