# Generated by Django 4.0.4 on 2022-08-01 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0003_alter_contacts_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Освіта')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Освіта')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='currency',
        ),
        migrations.AddField(
            model_name='candidate',
            name='desired_salary',
            field=models.PositiveIntegerField(blank=True, default=7000, null=True, verbose_name='Бажана зарплата (грн/міс.)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='intro',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Трохи про себе'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна вакансія'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 20, 26, 1, 67195), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 20, 26, 1, 69204), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 20, 26, 1, 64203), verbose_name='Дата додавання'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.educationlevel', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.experiencelevel', verbose_name='Досвід'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.educationlevel', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.experiencelevel', verbose_name='Досвід'),
        ),
    ]
