# Generated by Django 4.0.4 on 2022-05-25 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0005_alter_vacancy_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 22, 59, 3, 298765), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('₴', 'HRYVNIA'), ('$', 'DOLLAR'), ('€', 'EURO')], max_length=10, verbose_name='Валюта'),
        ),
    ]
