# Generated by Django 4.0.4 on 2022-08-01 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0005_fill_db_with_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name': 'Рівень освіти', 'verbose_name_plural': 'Рівень освіти'},
        ),
        migrations.AlterModelOptions(
            name='experiencelevel',
            options={'verbose_name': 'Рівень досвіду', 'verbose_name_plural': 'Рівень досвіду'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 22, 4, 30, 703282), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.educationlevel', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.experiencelevel', verbose_name='Досвід'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 22, 4, 30, 704282), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='experiencelevel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 22, 4, 30, 700282), verbose_name='Дата додавання'),
        ),
    ]
