# Generated by Django 4.0.4 on 2022-05-25 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0006_alter_vacancy_creation_date_alter_vacancy_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 23, 4, 2, 455340), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Зарплата'),
        ),
    ]
