# Generated by Django 4.0.4 on 2022-05-25 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0008_alter_vacancy_company_alter_vacancy_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 23, 28, 8, 693528), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис вакансії'),
        ),
    ]
