# Generated by Django 4.0.4 on 2022-05-25 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0009_alter_vacancy_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Опис команії'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 23, 30, 41, 389402), verbose_name='Дата додавання'),
        ),
    ]
