# Generated by Django 4.0.4 on 2022-05-26 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0010_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['company', 'salary'], 'verbose_name': 'Вакансії', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='categories',
            field=models.ManyToManyField(to='work4you_app.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work4you_app.company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 17, 54, 10, 525768), verbose_name='Дата додавання'),
        ),
    ]
