# Generated by Django 4.0.4 on 2022-05-26 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0011_alter_vacancy_options_remove_vacancy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис команії'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 23, 15, 21, 910563), verbose_name='Дата додавання'),
        ),
    ]
