# Generated by Django 4.0.4 on 2022-05-27 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0014_alter_company_image_alter_vacancy_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 0, 5, 52, 54386), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education_level',
            field=models.CharField(choices=[('Середня школа', 'Середня школа'), ('Старша школа', 'Старша школа'), ('Коледж', 'Коледж'), ('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр')], max_length=50, verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('Без досвіду', 'Без досвіду'), ('Пів року', 'Пів року'), ('Більше року', 'Більше року'), ('Більше 2 років', 'Більше 2 років'), ('Більше 5 років', 'Більше 5 років')], max_length=50, verbose_name='Досвід'),
        ),
    ]
