# Generated by Django 4.0.4 on 2022-05-27 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0015_alter_vacancy_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('Повна зайнятість', 'Повна зайнятість'), ('Неповна зайнятість', 'Неповна зайнятість'), ('Дистанційна робота', 'Дистанційна робота')], default=('Повна зайнятість', 'Повна зайнятість'), max_length=100, verbose_name='Тип зайнятості'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 0, 24, 27, 286644), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education_level',
            field=models.CharField(choices=[('середня школа', 'середня школа'), ('старша школа', 'старша школа'), ('коледж', 'коледж'), ('бакалавр', 'бакалавр'), ('магістр', 'магістр')], max_length=50, verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('без досвіду', 'без досвіду'), ('пів року', 'пів року'), ('більше року', 'більше року'), ('більше 2 років', 'більше 2 років'), ('більше 5 років', 'більше 5 років')], max_length=50, verbose_name='Досвід'),
        ),
    ]
