# Generated by Django 4.0.4 on 2022-05-29 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0017_alter_vacancy_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тип кандидата')),
            ],
            options={
                'verbose_name': 'Типи кандидатів',
                'verbose_name_plural': 'Типи кандидатів',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюти',
                'verbose_name_plural': 'Валюти',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Тип зайнятості')),
            ],
            options={
                'verbose_name': 'Типи зайнятості',
                'verbose_name_plural': 'Типи зайнятості',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_for_migrant',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_for_student',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='work4you_app.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Опис команії'),
        ),
        migrations.AlterField(
            model_name='company',
            name='workers_count',
            field=models.CharField(choices=[('0–10', '0–10'), ('20–50', '20–50'), ('50–100', '50–100'), ('100–500', '100–500'), ('500–1000+', '500–1000+')], default='10-20', max_length=20, verbose_name='Кількість пацівників'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 21, 8, 55, 377887), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Опис вакансії'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='candidate_types',
            field=models.ManyToManyField(to='work4you_app.candidatetype', verbose_name='Типи кандидатів'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.employmenttype', verbose_name='Тип зайнятості'),
        ),
    ]
