# Generated by Django 4.0.4 on 2022-05-29 20:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0018_candidatetype_currency_employmenttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-title', 'id'], 'verbose_name': 'Валюти', 'verbose_name_plural': 'Валюти'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidate_types',
            field=models.ManyToManyField(blank=True, null=True, to='work4you_app.candidatetype', verbose_name='Типи кандидатів'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 23, 32, 23, 519874), verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.ForeignKey(default='грн', max_length=15, on_delete=django.db.models.deletion.CASCADE, to='work4you_app.currency', verbose_name='Валюта'),
        ),
    ]
