# Generated by Django 4.0.4 on 2022-05-29 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work4you_app', '0019_alter_currency_options_alter_vacancy_candidate_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 23, 51, 31, 568378), verbose_name='Дата додавання'),
        ),
    ]
